### ISSUE TITLE
Metadata for each episode

### ISSUE THREAD

**Issue by fterbo** [davinkevin/Podcast-Server#100]
It would be nice to have at least a few pieces of metadata for each episode (with some way to view it):

* Played / Unplayed
* Last Played Date
* Duration / Length

**Comment by davinkevin** [comment]
**Duration / Length** is exposed by the API at `/api/podcasts/{idPodcast}/items/{id}`, but can be empty from some source which doesn't expose this value... 

**Played / Unplayed** and **Last Played Date** can't be retrieved because the application has for main goal to be accessed by external client (Kodi, RSS Reader like BeyondPod, Chromecast). Some of them download file before reading it (mostly rss reader), so we can't guess if a download have been viewed or not.

If you have a better idea, let me know

**Comment by fterbo** [comment]
I am mostly considering the local player metadata - why have a local UI if it doesn't maintain its own metadata?  This should be separate from what RSS clients do.

**Comment by davinkevin** [comment]
The UI is just an extra to expose data from the backend, as an strict alternative to consumption through external app (RSS Reader, Kodi & co...).

I don't plan to support this feature for now... I let you propose some code enhancement about this if you want to...
