### ISSUE TITLE
I'm guessing this is Linux only?

### ISSUE THREAD

**Issue by TonyWhitley** [davinkevin/Podcast-Server#133]
I ran the latest release .jar file on Windows and get the customary Java wall of text with errors buried in it.  The first one is 
`org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:/tmp/podcast-server". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-197]`

I'm not expecting anyone to port it to Windows but mentioning it at the top of the Description would save the time of the next Windows user to find your program.

**Comment by davinkevin** [comment]
Not really... I don't test it on windows because I didn't have windows on any of my computers. I think you can provide an environment variable to change the `/tmp/podcast-server` to something else, but...

...the jar you are using is a very old version and the right way to run the app is through docker images or kubernetes (with k3s). 

In those cases, you won't have any error about windows compatibility.
