### ISSUE TITLE
Upload to podcast not working

### ISSUE THREAD

**Issue by KingKarlo** [davinkevin/Podcast-Server#136]
What could I be doing wrong? I‘m using the latest docker image and basically everything is working fine.

But when I add a podcast with the type „Upload“ I‘m not able to upload any episodes to it.

The podcast appears in the podcast list, I can select it and switch to the tab „Upload“. But no matter what file type I drop there and no matter what browser or OS I use for it nothing happens.

Is there anything I might be missing?

**Comment by davinkevin** [comment]
First, thank you for opening the issue. The GitHub repository is a mirror, to open an issue, I advise you to go to https://gitlab.com/davinkevin/Podcast-Server/-/issues

To answer you, I think the problem is the filename format required to upload a file. Currently, you have to name your file like `<what-you-want> - yyyy-MM-dd - <title-of-your-episode>.<ext>`, for example this is a valid format: 

* `Uplooad podcast - 2020-06-03 - the title I want to show in the UI.mp4`
* `Another Podcast - 2019-01-06 - An old item.mp4`
* `Foo - 2021-06-03 - An episode in the futur.mp4`

There is no documentation on the project right now about it and the UI, under restructuration doesn't help at all sadly. If you want, you can contribute to the project to improve it!

If the problem is still present, I advise you to open another issue on https://gitlab.com/davinkevin/Podcast-Server/-/issues with log from the backend which is very helpful to provide support.
