### ISSUE TITLE
MultipartFileSender

### ISSUE THREAD

**Issue by andre77** [davinkevin/Podcast-Server#74]
https://github.com/davinkevin/Podcast-Server/blob/d927d9b8cb9ea1268af74316cd20b7192ca92da7/src/main/java/lan/dk/podcastserver/utils/multipart/MultipartFileSender.java#L304

Not directly an issue, but i did not find the way, where to ask the question else.
its not clear to me, why the input stream is skipped with "start" bytes?...
given the following situation:
Range:  bytes=10-20,30-50

we have two ranges here. the first time Range.copy is called with start: 10.
10 bytes are skipped from the input stream: correct so far.

the second time the copy method is called with start: 30
to skip 30 bytes is wrong, i believe... the correct value to skip would be 30-20-1=9 bytes. so is the code wrong? or where is the error in my reasoning ?

**Comment by davinkevin** [comment]
This class has a lot of interest... more than the project itself 😄 

Your comment is good, I will investigate on this as soon as possible. The code you see is an adaptation of [an old version](http://balusc.omnifaces.org/2009/02/fileservlet-supporting-resume-and.html), so I maybe port the bug too... 

To be honest, I don't think in my use-case, the multi-range is something widely used, because in video streaming, we only have one range at a time.

The problem here, is how to test it and assure the result is correct ? If you have and idea, I'll be glad to hear it, or review it in a PR.

Thanks

**Comment by davinkevin** [comment]
I've made the modification, but I realized, during more than one year of log, I never end up in the multipart case, so I can't validate at 100% the solution is correct 😢 . If you can test it in a representative env for that, it could be interesting.

I don't push my work on this part because "soon", a fix will be integrated to spring to add support to non-static resources : https://jira.spring.io/browse/SPR-13834
